import Head from 'next/head'
import {  useEffect, useRef, useState } from 'react'

function Home() {
  const codeAreaRef = useRef(null);
  const [message, setMessage] = useState(`
import React from "react";
import { StyleSheet, Text, View } from "react-native";

export default function test() {
  return (
    <View style={styles.container}>
      <Text style={styles.text}>Welcome to Expo + Next.js 👋</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    fontSize: 16,
  },
});
`);


  const handleCodeChange = (event) => {
    setMessage(event.target.value);
  }
  
  const runCode = async () => {
    await fetch('api/update', {
      method: 'POST',
      body: message
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className='left'>
          <textarea 
            ref={codeAreaRef.current}
            className='codearea'
            id="code"
            onChange={handleCodeChange}
            value={message}
          />
          <button onClick={runCode}>Run</button>
        </div>
        <div className='right'>
          <iframe src='./test' className='output' id="output"></iframe>
        </div>
      </div>
    </>
  )
}

export default Home;